### ISSUE TITLE
[Meta] Changes & Updates

### ISSUE THREAD

**Issue by emirkmo** [SNflows/flows-tools#15]
- [ ] Add generic instrument for finder chart.
- [ ] Pass basic type annot. from pyright.
- [ ] Get typing stubs from type shed for Mypy.
- [ ] Black the code.
- [ ] Increase test coverage and add end-to-end test/
- [ ] Add customization for the finder chart plot color.
- [ ] Add coverage report and pytest protection for Master branch PRs.
- [ ] Add service to use `tnsquery` (maybe also via tendrils), so we aren't solely reliant upon flows api tokens.
